Update ant-build.yml

diff --git a/.github/workflows/ant-build.yml b/.github/workflows/ant-build.yml
--- a/.github/workflows/ant-build.yml
+++ b/.github/workflows/ant-build.yml
@@ -15,7 +15,7 @@ on:
 
     outputs:
       issue_number:
-        description: "TCreated Issue ID"
+        description: "Created Issue ID"
         value: ${{ jobs.code-build.outputs.issue_number }}
 
 permissions:
@@ -62,7 +62,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     outputs:
-      issue_number: ${{ steps.parse_issue.outputs.issue_number }}
+      issue_number: ${{ steps.create_issue.outputs.issue-number }}
 
     steps:
       - name: Checkout Code
@@ -124,13 +124,13 @@ jobs:
           approvers: ${{ needs.Initialising.outputs.devops_ids }}
           secret: ${{ secrets.PEM_KEY }}
 
-      - name: Parse the Issue Number
-        id: parse_issue
-        run: |
-          ISSUE_NUMBER="${{ steps.create_issue.outputs.issue-number }}"
-          if [[ -z "$ISSUE_NUMBER" ]]; then
-            echo "❌ Issue number not found!"
-            exit 1
-          fi
-          echo "✅ Issue number is $ISSUE_NUMBER"
-          echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_OUTPUT"
+      # - name: Parse the Issue Number
+      #   id: parse_issue
+      #   run: |
+      #     ISSUE_NUMBER="${{ steps.create_issue.outputs.issue-number }}"
+      #     if [[ -z "$ISSUE_NUMBER" ]]; then
+      #       echo "❌ Issue number not found!"
+      #       exit 1
+      #     fi
+      #     echo "✅ Issue number is $ISSUE_NUMBER"
+      #     echo "issue-number=$ISSUE_NUMBER" >> "$GITHUB_OUTPUT"
